spring:
  profiles:
    active: test

---
#prod
spring:
  profiles: prod
server:
  port: 9999

---
#dev
spring:
  profiles: dev
server:
  port: 8888

---
#test
spring:
  profiles: test
server:
  port: 7777